# -*- eval: (cargo-minor-mode 1) -*-

[package]
workspace = ".."
name = "bitmap-font-codegen"
version = "0.0.0"
publish = false
authors = ["Dominic Meiser <git@msrd0.de>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
askama = "0.10"
base64 = "0.13"
bdf = { git = "https://github.com/msrd0/rust-bdf" }
bit-vec = "0.6"
linked-hash-map = "0.5.4"
num-format = "0.4"
